codecov:
  token: 977e1925-527b-41c3-9a32-a8b2b5767955

# Team Yaml
coverage:
  round: down
  precision: 5

# Repository Yaml
coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5